### ISSUE TITLE
RBD_CONF_KEYRING_KEY" not found 

### ISSUE THREAD

**Issue by chiel2603** [wetopi/docker-volume-rbd#12]
With command:
`docker plugin install wetopi/rbd --alias=wetopi/rbd LOG_LEVEL=1 RBD_CONF_KEYRING_USER=client.<name> RBD_CONF_KEYRING_KEY=<key>`

I get a:
Error response from daemon: setting "RBD_CONF_KEYRING_KEY" not found in the plugin configuration

**Comment by chiel2603** [comment]
Plug-in does not remind  settings even with the "docker plugin set" command and even within the config file.

**Comment by sitamet** [comment]
Try something like this:

```sh
docker plugin install --grant-all-permissions wetopi/rbd:2.0.1 --alias=wetopi/rbd \
LOG_LEVEL=1 \
RBD_CONF_CLUSTER={{rbd_cluster}} \
RBD_CONF_KEYRING_USER={{rbd_keyring_user}} \
RBD_CONF_POOL=mypoolname
```
