### ISSUE TITLE
arm64 build

### ISSUE THREAD

**Issue by psukys** [wetopi/docker-volume-rbd#17]
it would be good to have an arm64 build as well. By quick check, the image build and run without any foreseeable problems on the platform (built on Raspberry Pi 4)

**Comment by sitamet** [comment]
Please help with your pull request ;)

**Comment by sitamet** [comment]
@psukys we have published the version 4 with platform arm64: 

```
docker plugin install wetopi/rbd:4.0.0-arm64 \
  --alias=wetopi/rbd \
  LOG_LEVEL=1 \
  RBD_CONF_POOL="ssd" \
  RBD_CONF_CLUSTER=ceph \
  RBD_CONF_KEYRING_USER=client.admin
```
