### ISSUE TITLE
Not able to install with docker 19.03.11, build 42e35e6

### ISSUE THREAD

**Issue by stxShadow** [wetopi/docker-volume-rbd#18]
If i try to install on a raspberry pi (armhf) with
docker plugin install wetopi/rbd \
--alias=wetopi/rbd \
LOG_LEVEL=3 \
RBD_CONF_POOL="docker" \
RBD_CONF_CLUSTER=ceph \
RBD_CONF_KEYRING_USER=client.admin

i get: 

latest: Pulling from wetopi/rbd
4e00b2ce824b: Download complete 
Digest: sha256:8b2f17eb98718fa8bdf66791cabe5f734497836d9dd49c8d9a851e7c085ecb4b
Status: Downloaded newer image for wetopi/rbd:latest
Error response from daemon: dial unix /run/docker/plugins/a8317fcc280086285456f40799857452bc22970024d3de81c8a0dea03b715a9e/rbd.sock: connect: no such file or directory

any hints how fix this ?
Thx a lot

Jens

**Comment by cybercorey** [comment]
@stxShadow Did you ever find a fix to this?

Run into the same issue on raspberry pi 4 running Debian 11 64bit ARM

**Comment by cybercorey** [comment]
@stxShadow Did you ever find a fix to this?

Run into the same issue on raspberry pi 4 running Debian 11 64bit ARM

**Comment by stxShadow** [comment]
@cybercorey .... sadly: no .... i was not able to solf it myselfs and got no answer from the devs.

**Comment by sitamet** [comment]
@stxShadow @cybercorey what is the status of plugin.

does it give more info when enabling it? `docker plugin enable wetopi/rbd`

**Comment by cybercorey** [comment]
Ah I think I worked mine out and moved onto something else, the raspberry pi kernel lacks the rdb module.
