### ISSUE TITLE
Not working with docker 18.03

### ISSUE THREAD

**Issue by noonowl71** [wetopi/docker-volume-rbd#2]
I've been trying to setup the plugin on a docker 18.03 and I get this message:

```
root@node1:~# docker plugin install wetopi/rbd:1.0.1 --alias=wetopi/rbd LOG_LEVEL=3 RBD_CONF_POOL=docker RBD_CONF_CLUSTER=ceph RBD_CONF_KEYRING_USER=client.admin
Plugin "wetopi/rbd:1.0.1" is requesting the following privileges:
 - network: [host]
 - mount: [/lib/modules]
 - mount: [/dev]
 - mount: [/etc/ceph]
 - mount: [/sys]
 - allow-all-devices: [true]
 - capabilities: [CAP_SYS_ADMIN CAP_SYS_MODULE]
Do you grant the above permissions? [y/N] y
1.0.1: Pulling from wetopi/rbd
557c97aee32a: Download complete
Digest: sha256:0198a49200f30ebf808e007a7579f0d37f0a750edd47764ef8086eb7066d87ae
Status: Downloaded newer image for wetopi/rbd:1.0.1
Error response from daemon: dial unix /run/docker/plugins/1708b2e7ed0181744814aff4c15a96237f556a48fa7d2bdf13bbb86f667576ef/rbd.sock: connect: no such file or directory
```
Also after doing that my system becomes unstable because the /dev filsystem is messed up and i have to reboot:

```
root@node1:~# ll /dev/
total 4
drwxr-xr-x  5 root root  100 Apr  7 21:46 ./
drwxr-xr-x 24 root root 4096 Apr  7 20:25 ../
drwxrwxrwt  2 root root   40 Apr  7 21:46 mqueue/
drwxr-xr-x  2 root root    0 Apr  7 21:46 pts/
drwxrwxrwt  2 root root   40 Apr  7 21:46 shm/
```

Maybe it has to do with this #https://github.com/moby/moby/pull/35829 change on docker published on 18.03 version.

If you need more info just ask, thanks.

**Comment by noonowl71** [comment]
After digging more I think that it's related to a bug on docker:

https://github.com/moby/moby/issues/36698
https://github.com/moby/moby/pull/36711/files
https://github.com/docker/for-linux/issues/272

It will be fixed on 18.03.1, I will test when it's released and report again.

**Comment by sitamet** [comment]
You are right.
We have faced the same problem on 18.03.0 

We are running ok in 18.02.0-ce

**Comment by noonowl71** [comment]
Just tested with 18.03.1-ce and it's working now. Thanks

**Comment by sitamet** [comment]
@noonowl71 perfect! Thanks
