### ISSUE TITLE
Ubuntu 20.04.2 and Docker version 20.10.2 needs cpability CAP_NET_ADMIN

### ISSUE THREAD

**Issue by jhernandez-cefca** [wetopi/docker-volume-rbd#20]
The driver fail to create volumes in Ubuntu 20.04.2 with Docker version 20.10.2. Adding the capability CAP_NET_ADMIN for the driver, then it works. It maybe may occur in other Linux distributions with newer kernels.

**Comment by JvGinkel** [comment]
May I ask how you add this capability? I think I'm running into the same issue as you did with this error:

`
VolumeDriver.Create: volume-rbd Name=unable to open the ceph cluster connection: rados: ret=13, Permission denied Request=Create Message=unable to connect to rbd pool
`

Thanks

**Comment by JvGinkel** [comment]
I figured out how and after building the plugin with the `CAP_NET_ADMIN` added it's all working again.

**Comment by jhernandez-cefca** [comment]
Sorry, I am late in the response but maybe is useful for others:

# Get the Driver code and create a Docker image
wget https://github.com/wetopi/docker-volume-rbd/archive/refs/tags/3.0.0.zip
unzip 3.0.0.zip
cd docker-volume-rbd-3.0.0/
docker build --tag wetopi-CUSTOM:3.0.0 .

# Create a container to export the root file system to folder 'rootfs'
docker create wetopi-CUSTOM:3.0.0  # returns the container ID: 
d7cc170f6f8fe15b9fa83904d16df94a881698f8f81ed3a429c82a2df3b97db0 (will 
be different)
cd ..
mkdir wetopi-CUSTOM
cd mkdir wetopi-CUSTOM
mkdir rootfs
cd rootfs/
docker export 
d7cc170f6f8fe15b9fa83904d16df94a881698f8f81ed3a429c82a2df3b97db0 | tar 
-xvf -

# Copy and modify 'config.json'
cd ..
cp ../docker-volume-rbd-3.0.0/config.json .
nano config.json  # Add CAP_NET_ADMIN to capabilities

# Create the plugin in Docker from the directory
docker plugin create wetopi-CUSTOM:3.0.0 .

# Initialize and enable (adjust for your system)
docker plugin set RBD_CONF_POOL=rbd RBD_CONF_CLUSTER=ceph 
RBD_CONF_KEYRING_USER=client.user
docker plugin enable wetopi-CUSTOM:3.0.0
docker plugin ls

**Comment by sitamet** [comment]
@jhernandez-cefca there is no need to compile a new driver to modify config.

**Comment by JvGinkel** [comment]
Maybe you can tell us how to fix this issue then?

**Comment by sitamet** [comment]
We are pushing a new release 3.0.1 CAP_NET_ADMIN

**Comment by JvGinkel** [comment]
I noticed c89b9e6 can you also create a release? Thanks

**Comment by sitamet** [comment]
@JvGinkel release tagged sorry
