### ISSUE TITLE
encountered an issue with resizing the RBD disk.

### ISSUE THREAD

**Issue by steven3579** [wetopi/docker-volume-rbd#27]
I used the Ceph interface to resize a volume from its default size of 1024MB to 5GB. However, on my Docker server, it still recognizes the size as 1024MB. I've tried various methods, but none have yielded results. Has anyone else encountered a similar situation?

I run command:
 docker run -it -v $(docker volume create -d rbd-volume -o size=1024 busybox_volume):/data --volume-driver=rbd-volume busybox
![Screenshot from 2024-05-16 10-08-57](https://github.com/wetopi/docker-volume-rbd/assets/32231942/222e4ba0-8fe5-4720-a4c2-bff4ce26e187)
![Screenshot from 2024-05-16 10-10-48](https://github.com/wetopi/docker-volume-rbd/assets/32231942/ce59350c-6dc7-45e7-9ae6-1a78ecdfde0f)

**Comment by sitamet** [comment]
Not sure about ceph interface. 
Here a comand-line process:

```sh
# 1. inspect current size [optional]: 
rbd info ssd/busybox_volume
 
# 2. repair ext4:
rbd map ssd/busybox_volume
# /dev/rbd0
fsck.ext4 /dev/rbd0
 
# 3. inspect current content usage [optional]:
mkdir /mnt/joan
mount /dev/rbd0 /mnt/joan
df -h /mnt/joan
umount /mnt/joan
rmdir /mnt/joan
 
# 4. resize rbd volume. Sometimes the MMP gives an alert, follow the suggested command
rbd resize --size 160G ssd/busybox_volume
 
 
# 5. resize the ext4 fs:

# clean the MMP (multiple mount protection)
tune2fs -f -E clear_mmp /dev/rbd0
e2fsck -f /dev/rbd0
resize2fs /dev/rbd0
 
 
# 6. unmap the device:
rbd unmap ssd/busybox_volume
```

**Comment by steven3579** [comment]
> Not sure about ceph interface. Here a comand-line process:
> 
> ```shell
> # 1. inspect current size [optional]: 
> rbd info ssd/busybox_volume
>  
> # 2. repair ext4:
> rbd map ssd/busybox_volume
> # /dev/rbd0
> fsck.ext4 /dev/rbd0
>  
> # 3. inspect current content usage [optional]:
> mkdir /mnt/joan
> mount /dev/rbd0 /mnt/joan
> df -h /mnt/joan
> umount /mnt/joan
> rmdir /mnt/joan
>  
> # 4. resize rbd volume. Sometimes the MMP gives an alert, follow the suggested command
> rbd resize --size 160G ssd/busybox_volume
>  
>  
> # 5. resize the ext4 fs:
> 
> # clean the MMP (multiple mount protection)
> tune2fs -f -E clear_mmp /dev/rbd0
> e2fsck -f /dev/rbd0
> resize2fs /dev/rbd0
>  
>  
> # 6. unmap the device:
> rbd unmap ssd/busybox_volume
> ```

It's working. Thank you for your help.
